site:
  title: "📰 Daily News - Fresh & Current"
  tagline: "Latest AI developments and economics/politics news (max 7 days old)"
  num_items_per_feed: 15
  villager_greeting: "Only the freshest news, guaranteed within the last week!"

feeds:
  ai_frontier:
    - name: "Wall Street Journal Tech"
      url: "https://feeds.a.dj.com/rss/RSSWSJD.xml"
    - name: "Financial Times Tech"
      url: "https://www.ft.com/technology?format=rss"
    - name: "Reuters Technology"
      url: "https://feeds.reuters.com/reuters/technologyNews"
    - name: "Bloomberg Technology"
      url: "https://feeds.bloomberg.com/technology/news.rss"
    - name: "BBC Technology"
      url: "http://feeds.bbci.co.uk/news/technology/rss.xml"
    - name: "CNN Business Tech"
      url: "http://rss.cnn.com/rss/edition_technology.rss"
    - name: "The Economist Technology"
      url: "https://www.economist.com/science-and-technology/rss.xml"
    - name: "MIT Technology Review"
      url: "https://www.technologyreview.com/feed/"

  economics_politics:
    - name: "Wall Street Journal"
      url: "https://feeds.a.dj.com/rss/RSSWorldNews.xml"
    - name: "Wall Street Journal Business"
      url: "https://feeds.a.dj.com/rss/WSJcomUSBusiness.xml"
    - name: "Financial Times"
      url: "https://www.ft.com/world?format=rss"
    - name: "Financial Times Economics"
      url: "https://www.ft.com/global-economy?format=rss"
    - name: "Reuters Business"
      url: "https://feeds.reuters.com/reuters/businessNews"
    - name: "Reuters Politics"
      url: "https://feeds.reuters.com/Reuters/PoliticsNews"
    - name: "Bloomberg Politics"
      url: "https://feeds.bloomberg.com/politics/news.rss"
    - name: "Bloomberg Economics"
      url: "https://feeds.bloomberg.com/economics/news.rss"
    - name: "The Economist"
      url: "https://www.economist.com/latest/rss.xml"
    - name: "Associated Press Politics"
      url: "https://feeds.apnews.com/apf-politics"
    - name: "Associated Press Business"
      url: "https://feeds.apnews.com/apf-usbusiness"
    - name: "BBC Business"
      url: "http://feeds.bbci.co.uk/news/business/rss.xml"
    - name: "BBC Politics"
      url: "http://feeds.bbci.co.uk/news/politics/rss.xml"
    - name: "CNN Politics"
      url: "http://rss.cnn.com/rss/politics.rss"
    - name: "CNN Business"
      url: "http://rss.cnn.com/rss/money_latest.rss"
    - name: "Politico"
      url: "https://www.politico.com/rss/politicopicks.xml"
    - name: "NPR Politics"
      url: "https://feeds.npr.org/1014/feed.json"

colors:
  primary: "#8FBC8F"      # Sage green like Animal Crossing
  secondary: "#F0E68C"    # Khaki yellow
  accent: "#FFB6C1"       # Light pink
  background: "#F5F5DC"   # Beige
  text: "#2F4F4F"         # Dark slate gray
  button: "#98FB98"       # Pale green
